# Generated by Django 4.2.29 on 2026-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_workrequest_workrequestattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('ACCEPTED', 'Accepted')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PROPOSED', 'Proposed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
